-- ============================================================
-- VALHALLA - SCRIPT CONSOLIDADO
-- Baseado no DER de merge aprovado
-- PostgreSQL
--
-- Decisões:
--   * UUID para entidades principais/expostas
--   * INT/BIGINT para domínio interno e tabelas de alto volume
--   * TIMESTAMP para datas
--   * 2FA removido
--   * sessão JWT mantida
--   * status de usuário textual
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. ORGANIZAÇÃO E ACESSO
-- ============================================================

CREATE TABLE estabelecimento (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    razao_social VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(150) NOT NULL,
    cnpj VARCHAR(14) NOT NULL,
    inscricao_estadual VARCHAR(20),
    email_contato VARCHAR(255),
    telefone VARCHAR(20),
    cep VARCHAR(8),
    logradouro VARCHAR(150),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_estabelecimento_cnpj UNIQUE (cnpj)
);

CREATE TABLE perfil (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id UUID NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_perfil_estabelecimento
        UNIQUE (id, estabelecimento_id),

    CONSTRAINT uq_perfil_nome_estabelecimento
        UNIQUE (estabelecimento_id, nome),

    CONSTRAINT fk_perfil_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id)
);

CREATE TABLE funcionalidade (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,

    CONSTRAINT uq_funcionalidade_codigo UNIQUE (codigo)
);

CREATE TABLE perfil_funcionalidade (
    perfil_id INT NOT NULL,
    funcionalidade_id INT NOT NULL,

    CONSTRAINT pk_perfil_funcionalidade
        PRIMARY KEY (perfil_id, funcionalidade_id),

    CONSTRAINT fk_perfil_funcionalidade_perfil
        FOREIGN KEY (perfil_id)
        REFERENCES perfil(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_perfil_funcionalidade_funcionalidade
        FOREIGN KEY (funcionalidade_id)
        REFERENCES funcionalidade(id)
        ON DELETE CASCADE
);

-- ============================================================
-- 2. USUÁRIOS E PREFERÊNCIAS
-- ============================================================

CREATE TABLE usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estabelecimento_id UUID NOT NULL,
    perfil_id INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(13),
    senha_hash VARCHAR(255) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',

    tentativas_login INT NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMP,
    ultimo_login_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_usuario_status
        CHECK (status IN ('ATIVO', 'INATIVO')),

    CONSTRAINT chk_usuario_tentativas_login
        CHECK (tentativas_login >= 0),

    CONSTRAINT fk_usuario_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id),

    -- Impede um usuário de receber perfil pertencente a outro estabelecimento.
    CONSTRAINT fk_usuario_perfil_estabelecimento
        FOREIGN KEY (perfil_id, estabelecimento_id)
        REFERENCES perfil(id, estabelecimento_id)
);

-- E-mail único sem diferenciar maiúsculas/minúsculas.
CREATE UNIQUE INDEX uq_usuario_email_lower
    ON usuario (LOWER(email));

-- Permissões adicionais atribuídas diretamente a um usuário.
-- As permissões do perfil continuam válidas; esta tabela apenas as complementa.
CREATE TABLE usuario_funcionalidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL,
    funcionalidade_id INT NOT NULL,
    efeito VARCHAR(10) NOT NULL,
    CONSTRAINT uq_usuario_funcionalidade UNIQUE (usuario_id, funcionalidade_id),
    CONSTRAINT ck_usuario_funcionalidade_efeito CHECK (efeito IN ('GRANT', 'REVOKE')),
    CONSTRAINT fk_usuario_funcionalidade_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_funcionalidade_funcionalidade FOREIGN KEY (funcionalidade_id)
        REFERENCES funcionalidade(id) ON DELETE CASCADE
);

CREATE TABLE preferencia_notificacao (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL,
    evento VARCHAR(80) NOT NULL,
    notificar_email BOOLEAN NOT NULL DEFAULT FALSE,
    notificar_push BOOLEAN NOT NULL DEFAULT FALSE,
    notificar_sistema BOOLEAN NOT NULL DEFAULT TRUE,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_preferencia_notificacao_usuario_evento
        UNIQUE (usuario_id, evento),

    CONSTRAINT fk_preferencia_notificacao_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE CASCADE
);

CREATE TABLE sessao_usuario (
    usuario_id UUID PRIMARY KEY,
    access_jti UUID NOT NULL,
    refresh_jti UUID NOT NULL,
    expira_em TIMESTAMP NOT NULL,

    CONSTRAINT uq_sessao_access_jti UNIQUE (access_jti),
    CONSTRAINT uq_sessao_refresh_jti UNIQUE (refresh_jti),

    CONSTRAINT fk_sessao_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE CASCADE
);

-- ============================================================
-- 3. CATÁLOGO E ESTOQUE
-- ============================================================

CREATE TABLE categoria (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id UUID NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categoria_nome_estabelecimento
        UNIQUE (estabelecimento_id, nome),

    CONSTRAINT fk_categoria_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id)
);

CREATE TABLE produto (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estabelecimento_id UUID NOT NULL,
    categoria_id INT NOT NULL,
    sku VARCHAR(45) NOT NULL,
    codigo_barras VARCHAR(45),
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    unidade_medida VARCHAR(10) NOT NULL,
    preco_custo NUMERIC(12,2),
    preco_venda NUMERIC(12,2) NOT NULL,
    ncm VARCHAR(8),
    cest VARCHAR(7),
    fracionado BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_produto_sku_estabelecimento
        UNIQUE (estabelecimento_id, sku),

    CONSTRAINT chk_produto_preco_custo
        CHECK (preco_custo IS NULL OR preco_custo >= 0),

    CONSTRAINT chk_produto_preco_venda
        CHECK (preco_venda >= 0),

    CONSTRAINT fk_produto_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id),

    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id)
);

CREATE TABLE estoque (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id UUID NOT NULL,
    quantidade_atual NUMERIC(12,3) NOT NULL DEFAULT 0,
    quantidade_reservada NUMERIC(12,3) NOT NULL DEFAULT 0,
    estoque_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_estoque_produto UNIQUE (produto_id),

    CONSTRAINT chk_estoque_quantidade_reservada
        CHECK (quantidade_reservada >= 0),

    CONSTRAINT chk_estoque_minimo
        CHECK (estoque_minimo >= 0),

    CONSTRAINT fk_estoque_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id)
);

-- ============================================================
-- 4. ORÇAMENTO E PEDIDO
-- ============================================================

CREATE TABLE orcamento (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estabelecimento_id UUID NOT NULL,
    operador_usuario_id UUID NOT NULL,
    numero BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    nome_cliente VARCHAR(150),
    documento_cliente VARCHAR(20),
    data_validade TIMESTAMP,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_orcamento_numero_estabelecimento
        UNIQUE (estabelecimento_id, numero),

    CONSTRAINT chk_orcamento_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_orcamento_desconto CHECK (desconto >= 0),
    CONSTRAINT chk_orcamento_total CHECK (total >= 0),

    CONSTRAINT fk_orcamento_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id),

    CONSTRAINT fk_orcamento_operador
        FOREIGN KEY (operador_usuario_id)
        REFERENCES usuario(id)
);

CREATE TABLE item_orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id UUID NOT NULL,
    produto_id UUID NOT NULL,
    descricao_produto VARCHAR(150) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    preco_unitario NUMERIC(12,2) NOT NULL,
    desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT chk_item_orcamento_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_item_orcamento_preco CHECK (preco_unitario >= 0),
    CONSTRAINT chk_item_orcamento_desconto CHECK (desconto >= 0),
    CONSTRAINT chk_item_orcamento_subtotal CHECK (subtotal >= 0),

    CONSTRAINT fk_item_orcamento_orcamento
        FOREIGN KEY (orcamento_id)
        REFERENCES orcamento(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_item_orcamento_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id)
);

CREATE TABLE pedido (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estabelecimento_id UUID NOT NULL,
    operador_usuario_id UUID NOT NULL,
    orcamento_id UUID,
    numero BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    nome_cliente VARCHAR(150),
    documento_cliente VARCHAR(20),
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concluido_em TIMESTAMP,
    cancelado_em TIMESTAMP,

    CONSTRAINT uq_pedido_numero_estabelecimento
        UNIQUE (estabelecimento_id, numero),

    CONSTRAINT chk_pedido_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_pedido_desconto CHECK (desconto >= 0),
    CONSTRAINT chk_pedido_total CHECK (total >= 0),

    CONSTRAINT fk_pedido_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id),

    CONSTRAINT fk_pedido_operador
        FOREIGN KEY (operador_usuario_id)
        REFERENCES usuario(id),

    CONSTRAINT fk_pedido_orcamento
        FOREIGN KEY (orcamento_id)
        REFERENCES orcamento(id)
);

CREATE TABLE item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id UUID NOT NULL,
    produto_id UUID NOT NULL,
    item_orcamento_id BIGINT,
    descricao_produto VARCHAR(150) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    preco_unitario NUMERIC(12,2) NOT NULL,
    desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT chk_item_pedido_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_item_pedido_preco CHECK (preco_unitario >= 0),
    CONSTRAINT chk_item_pedido_desconto CHECK (desconto >= 0),
    CONSTRAINT chk_item_pedido_subtotal CHECK (subtotal >= 0),

    CONSTRAINT fk_item_pedido_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedido(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_item_pedido_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id),

    CONSTRAINT fk_item_pedido_item_orcamento
        FOREIGN KEY (item_orcamento_id)
        REFERENCES item_orcamento(id)
);

CREATE TABLE pagamento_pedido (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pedido_id UUID NOT NULL,
    forma VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    valor NUMERIC(12,2) NOT NULL,
    referencia_externa VARCHAR(150),
    pago_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_pagamento_valor CHECK (valor > 0),

    CONSTRAINT fk_pagamento_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedido(id)
        ON DELETE CASCADE
);

-- ============================================================
-- 5. FISCAL
-- ============================================================

CREATE TABLE nota_fiscal (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estabelecimento_id UUID NOT NULL,
    pedido_id UUID,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    numero VARCHAR(20),
    serie VARCHAR(10),
    chave_acesso CHAR(44),
    contraparte_nome VARCHAR(150),
    contraparte_documento VARCHAR(20),
    valor_produtos NUMERIC(12,2) NOT NULL DEFAULT 0,
    valor_desconto NUMERIC(12,2) NOT NULL DEFAULT 0,
    valor_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    dados_fiscais JSONB,
    emitida_em TIMESTAMP,
    criada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_nota_fiscal_chave_acesso UNIQUE (chave_acesso),

    CONSTRAINT chk_nota_valor_produtos CHECK (valor_produtos >= 0),
    CONSTRAINT chk_nota_valor_desconto CHECK (valor_desconto >= 0),
    CONSTRAINT chk_nota_valor_total CHECK (valor_total >= 0),

    CONSTRAINT fk_nota_fiscal_estabelecimento
        FOREIGN KEY (estabelecimento_id)
        REFERENCES estabelecimento(id),

    CONSTRAINT fk_nota_fiscal_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedido(id)
);

CREATE TABLE item_nota_fiscal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_fiscal_id UUID NOT NULL,
    produto_id UUID,
    item_pedido_id BIGINT,
    descricao_produto VARCHAR(150) NOT NULL,
    ncm VARCHAR(8),
    cfop VARCHAR(4),
    quantidade NUMERIC(12,3) NOT NULL,
    preco_unitario NUMERIC(12,2) NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    dados_tributarios JSONB,

    CONSTRAINT chk_item_nota_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_item_nota_preco CHECK (preco_unitario >= 0),
    CONSTRAINT chk_item_nota_valor_total CHECK (valor_total >= 0),

    CONSTRAINT fk_item_nota_fiscal_nota
        FOREIGN KEY (nota_fiscal_id)
        REFERENCES nota_fiscal(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_item_nota_fiscal_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id),

    CONSTRAINT fk_item_nota_fiscal_item_pedido
        FOREIGN KEY (item_pedido_id)
        REFERENCES item_pedido(id)
);

-- ============================================================
-- 6. MOVIMENTAÇÃO DE ESTOQUE
-- ============================================================

CREATE TABLE movimentacao_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estoque_id INT NOT NULL,
    usuario_id UUID NOT NULL,
    item_pedido_id BIGINT,
    item_nota_fiscal_id BIGINT,
    tipo VARCHAR(30) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    saldo_anterior NUMERIC(12,3) NOT NULL,
    saldo_posterior NUMERIC(12,3) NOT NULL,
    motivo TEXT,
    ocorrido_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_movimentacao_quantidade CHECK (quantidade > 0),

    CONSTRAINT fk_movimentacao_estoque
        FOREIGN KEY (estoque_id)
        REFERENCES estoque(id),

    CONSTRAINT fk_movimentacao_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id),

    CONSTRAINT fk_movimentacao_item_pedido
        FOREIGN KEY (item_pedido_id)
        REFERENCES item_pedido(id),

    CONSTRAINT fk_movimentacao_item_nota_fiscal
        FOREIGN KEY (item_nota_fiscal_id)
        REFERENCES item_nota_fiscal(id)
);

-- ============================================================
-- ÍNDICES DE APOIO
-- ============================================================

CREATE INDEX idx_perfil_estabelecimento
    ON perfil(estabelecimento_id);

CREATE INDEX idx_usuario_estabelecimento
    ON usuario(estabelecimento_id);

CREATE INDEX idx_usuario_perfil
    ON usuario(perfil_id);

CREATE INDEX idx_usuario_funcionalidade_funcionalidade
    ON usuario_funcionalidade(funcionalidade_id);

CREATE INDEX idx_preferencia_usuario
    ON preferencia_notificacao(usuario_id);

CREATE INDEX idx_categoria_estabelecimento
    ON categoria(estabelecimento_id);

CREATE INDEX idx_produto_estabelecimento
    ON produto(estabelecimento_id);

CREATE INDEX idx_produto_categoria
    ON produto(categoria_id);

CREATE INDEX idx_produto_codigo_barras
    ON produto(codigo_barras);

CREATE INDEX idx_orcamento_estabelecimento
    ON orcamento(estabelecimento_id);

CREATE INDEX idx_orcamento_operador
    ON orcamento(operador_usuario_id);

CREATE INDEX idx_item_orcamento_orcamento
    ON item_orcamento(orcamento_id);

CREATE INDEX idx_pedido_estabelecimento
    ON pedido(estabelecimento_id);

CREATE INDEX idx_pedido_operador
    ON pedido(operador_usuario_id);

CREATE INDEX idx_pedido_orcamento
    ON pedido(orcamento_id);

CREATE INDEX idx_item_pedido_pedido
    ON item_pedido(pedido_id);

CREATE INDEX idx_pagamento_pedido
    ON pagamento_pedido(pedido_id);

CREATE INDEX idx_nota_fiscal_estabelecimento
    ON nota_fiscal(estabelecimento_id);

CREATE INDEX idx_nota_fiscal_pedido
    ON nota_fiscal(pedido_id);

CREATE INDEX idx_item_nota_fiscal_nota
    ON item_nota_fiscal(nota_fiscal_id);

CREATE INDEX idx_movimentacao_estoque
    ON movimentacao_estoque(estoque_id);

CREATE INDEX idx_movimentacao_usuario
    ON movimentacao_estoque(usuario_id);

CREATE INDEX idx_movimentacao_ocorrido_em
    ON movimentacao_estoque(ocorrido_em);

-- ============================================================
-- DOCUMENTAÇÃO DA ESTRATÉGIA DE IDS
-- ============================================================

COMMENT ON COLUMN estabelecimento.id IS
    'UUID - entidade principal exposta externamente';

COMMENT ON COLUMN perfil.id IS
    'INT - tabela de domínio interno';

COMMENT ON COLUMN funcionalidade.id IS
    'INT - tabela de domínio interno';

COMMENT ON COLUMN usuario.id IS
    'UUID - entidade principal e segurança do usuário';

COMMENT ON COLUMN preferencia_notificacao.id IS
    'INT - configuração interna do usuário';

COMMENT ON COLUMN categoria.id IS
    'INT - tabela de domínio interno e baixa cardinalidade';

COMMENT ON COLUMN produto.id IS
    'UUID - entidade exposta em APIs e operações comerciais';

COMMENT ON COLUMN estoque.id IS
    'INT - entidade interna vinculada ao produto';

COMMENT ON COLUMN orcamento.id IS
    'UUID - documento comercial compartilhável externamente';

COMMENT ON COLUMN item_orcamento.id IS
    'BIGINT - alto volume e escopo interno ao orçamento';

COMMENT ON COLUMN pedido.id IS
    'UUID - documento comercial e rastreamento externo';

COMMENT ON COLUMN item_pedido.id IS
    'BIGINT - alto volume e escopo interno ao pedido';

COMMENT ON COLUMN pagamento_pedido.id IS
    'UUID - transação que pode possuir referência externa';

COMMENT ON COLUMN nota_fiscal.id IS
    'UUID - documento fiscal exposto externamente';

COMMENT ON COLUMN item_nota_fiscal.id IS
    'BIGINT - alto volume e escopo interno à nota fiscal';

COMMENT ON COLUMN movimentacao_estoque.id IS
    'BIGINT - tabela de alto volume e histórico de estoque';
