-- Migra bancos criados antes do suporte a permissões individuais.
-- O script consolidado (db/script.sql) continua sendo a fonte para bancos novos.

DO $$
BEGIN
    IF to_regclass('public.usuario') IS NULL
        OR to_regclass('public.funcionalidade') IS NULL THEN
        RAISE EXCEPTION
            'A estrutura base não foi encontrada. Em um banco vazio, execute db/script.sql antes de iniciar a aplicação.';
    END IF;

    IF to_regclass('public.usuario_funcionalidade') IS NULL THEN
        CREATE TABLE usuario_funcionalidade (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id UUID NOT NULL,
            funcionalidade_id INT NOT NULL,
            efeito VARCHAR(10) NOT NULL,
            CONSTRAINT uq_usuario_funcionalidade UNIQUE (usuario_id, funcionalidade_id),
            CONSTRAINT ck_usuario_funcionalidade_efeito CHECK (efeito IN ('GRANT', 'REVOKE')),
            CONSTRAINT fk_usuario_funcionalidade_usuario FOREIGN KEY (usuario_id)
                REFERENCES usuario(id) ON DELETE CASCADE,
            CONSTRAINT fk_usuario_funcionalidade_funcionalidade FOREIGN KEY (funcionalidade_id)
                REFERENCES funcionalidade(id) ON DELETE CASCADE
        );
    END IF;
END $$;

-- Versões antigas da tabela possuíam apenas a associação usuário/funcionalidade.
ALTER TABLE usuario_funcionalidade
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS efeito VARCHAR(10);

UPDATE usuario_funcionalidade
SET efeito = 'GRANT'
WHERE efeito IS NULL;

ALTER TABLE usuario_funcionalidade
    ALTER COLUMN efeito SET NOT NULL;

DO $$
DECLARE
    primary_key_name TEXT;
BEGIN
    SELECT constraint_name
    INTO primary_key_name
    FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'usuario_funcionalidade'
      AND constraint_type = 'PRIMARY KEY';

    IF primary_key_name IS NOT NULL AND primary_key_name <> 'pk_usuario_funcionalidade' THEN
        EXECUTE format('ALTER TABLE usuario_funcionalidade DROP CONSTRAINT %I', primary_key_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'usuario_funcionalidade'
          AND constraint_name = 'pk_usuario_funcionalidade'
    ) THEN
        ALTER TABLE usuario_funcionalidade
            ADD CONSTRAINT pk_usuario_funcionalidade PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'usuario_funcionalidade'
          AND constraint_name = 'uq_usuario_funcionalidade'
    ) THEN
        ALTER TABLE usuario_funcionalidade
            ADD CONSTRAINT uq_usuario_funcionalidade UNIQUE (usuario_id, funcionalidade_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'usuario_funcionalidade'
          AND constraint_name = 'ck_usuario_funcionalidade_efeito'
    ) THEN
        ALTER TABLE usuario_funcionalidade
            ADD CONSTRAINT ck_usuario_funcionalidade_efeito CHECK (efeito IN ('GRANT', 'REVOKE'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_usuario_funcionalidade_funcionalidade
    ON usuario_funcionalidade(funcionalidade_id);
