-- Produto passa a distinguir itens estocáveis de receitas de drinks.
ALTER TABLE produto
    ADD COLUMN IF NOT EXISTS tipo VARCHAR(15) NOT NULL DEFAULT 'PADRAO',
    ADD COLUMN IF NOT EXISTS volume_embalagem_ml NUMERIC(12,3);

ALTER TABLE produto
    ALTER COLUMN preco_custo SET DEFAULT 0;

UPDATE produto
SET preco_custo = 0
WHERE preco_custo IS NULL;

ALTER TABLE produto
    ALTER COLUMN preco_custo SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'produto'::regclass AND conname = 'ck_produto_tipo'
    ) THEN
        ALTER TABLE produto ADD CONSTRAINT ck_produto_tipo
            CHECK (tipo IN ('PADRAO', 'DRINK')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'produto'::regclass AND conname = 'ck_produto_volume_embalagem'
    ) THEN
        ALTER TABLE produto ADD CONSTRAINT ck_produto_volume_embalagem
            CHECK (volume_embalagem_ml IS NULL OR volume_embalagem_ml > 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'produto'::regclass AND conname = 'ck_produto_preco_venda_positivo'
    ) THEN
        ALTER TABLE produto ADD CONSTRAINT ck_produto_preco_venda_positivo
            CHECK (preco_venda > 0) NOT VALID;
    END IF;
END $$;

-- Estoque mínimo não é obrigatório. Valores zero existentes representam ausência
-- de mínimo configurado e passam a ser nulos para permitir essa distinção.
UPDATE estoque
SET estoque_minimo = NULL
WHERE estoque_minimo = 0;

ALTER TABLE estoque
    ALTER COLUMN estoque_minimo DROP NOT NULL,
    ALTER COLUMN estoque_minimo DROP DEFAULT;

-- Uma receita associa um produto do tipo DRINK aos produtos consumidos por ele.
-- A regra de tipos (DRINK como pai e PADRAO como ingrediente) será validada na aplicação.
CREATE TABLE IF NOT EXISTS composicao_drink (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drink_id UUID NOT NULL,
    produto_id UUID NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    unidade_consumo VARCHAR(10) NOT NULL DEFAULT 'ML',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_composicao_drink_ingrediente UNIQUE (drink_id, produto_id),
    CONSTRAINT ck_composicao_drink_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_composicao_drink_unidade CHECK (unidade_consumo = 'ML'),
    CONSTRAINT ck_composicao_drink_autorreferencia CHECK (drink_id <> produto_id),
    CONSTRAINT fk_composicao_drink_drink FOREIGN KEY (drink_id)
        REFERENCES produto(id),
    CONSTRAINT fk_composicao_drink_produto FOREIGN KEY (produto_id)
        REFERENCES produto(id)
);

CREATE INDEX IF NOT EXISTS idx_composicao_drink_drink
    ON composicao_drink(drink_id);

CREATE INDEX IF NOT EXISTS idx_composicao_drink_produto
    ON composicao_drink(produto_id);

-- A movimentação registra dados de entrada e a origem da baixa de ingredientes de drinks.
ALTER TABLE movimentacao_estoque
    ADD COLUMN IF NOT EXISTS lote VARCHAR(100),
    ADD COLUMN IF NOT EXISTS numero_nota_fiscal VARCHAR(50),
    ADD COLUMN IF NOT EXISTS origem_drink_id UUID,
    ADD COLUMN IF NOT EXISTS receita_aplicada JSONB;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'movimentacao_estoque'::regclass
          AND conname = 'fk_movimentacao_origem_drink'
    ) THEN
        ALTER TABLE movimentacao_estoque
            ADD CONSTRAINT fk_movimentacao_origem_drink
            FOREIGN KEY (origem_drink_id) REFERENCES produto(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'movimentacao_estoque'::regclass
          AND conname = 'ck_movimentacao_tipo'
    ) THEN
        ALTER TABLE movimentacao_estoque ADD CONSTRAINT ck_movimentacao_tipo CHECK (
            tipo IN (
                'ENTRADA_INICIAL',
                'ENTRADA',
                'SAIDA',
                'AJUSTE_POSITIVO',
                'AJUSTE_NEGATIVO',
                'PERDA',
                'SAIDA_DRINK'
            )
        ) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'movimentacao_estoque'::regclass
          AND conname = 'ck_movimentacao_saida_drink_origem'
    ) THEN
        ALTER TABLE movimentacao_estoque
            ADD CONSTRAINT ck_movimentacao_saida_drink_origem CHECK (
                tipo <> 'SAIDA_DRINK' OR origem_drink_id IS NOT NULL
            ) NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_movimentacao_estoque_ocorrido_em
    ON movimentacao_estoque(estoque_id, ocorrido_em DESC);

CREATE INDEX IF NOT EXISTS idx_movimentacao_origem_drink
    ON movimentacao_estoque(origem_drink_id)
    WHERE origem_drink_id IS NOT NULL;
